export interface IAssociateDetails {
    MarketUnit: string,
    AssociateID: string,
    AssociateName: string,
    AccountID: string,
    AccountName: string,
    ParentCustomerName: string,
    Status: string,
    AssociateResponsetoPersonalDeviceAvailabilitySurvey: string,
    FinalMISDepartment: string,
    Location: string,
    CurrentEnabledForWFH: string,
    IfYesMethod: string,
    Comments: string,
    IsTheResourceProductiveFromHome: string,
    AddressOfShipping: string,
    Contact: string,
    LaptopRequested: string,
    CorporateStatusLaptop: string,
    DesktopRequested: string,
    CorporateStatusDesktop: string,
    RecordType: string,
    Sort: string,
    Temporary: string,
    AlwaysNew2: string,
    DuplicateFlag: string,
    PersonalReason: string,
    AssetId: string,
    PIIDataAccess: string,
    Protocol: string,
    BYODCompliance: string,
    Dongles: string,
    Allocation: string
}

export class AssociateDetails implements IAssociateDetails {
    constructor(
        public MarketUnit: string,
        public AssociateID: string,
        public AssociateName: string,
        public AccountID: string,
        public AccountName: string,
        public ParentCustomerName: string,
        public Status: string,
        public AssociateResponsetoPersonalDeviceAvailabilitySurvey: string,
        public FinalMISDepartment: string,
        public Location: string,
        public CurrentEnabledForWFH: string,
        public IfYesMethod: string,
        public Comments: string,
        public IsTheResourceProductiveFromHome: string,
        public AddressOfShipping: string,
        public Contact: string,
        public LaptopRequested: string,
        public CorporateStatusLaptop: string,
        public DesktopRequested: string,
        public CorporateStatusDesktop: string,
        public RecordType: string,
        public Sort: string,
        public Temporary: string,
        public AlwaysNew2: string,
        public DuplicateFlag: string,
        public PersonalReason: string,
        public AssetId: string,
        public PIIDataAccess: string,
        public Protocol: string,
        public BYODCompliance: string,
        public Dongles: string,
        public Allocation: string) {
    }
}